//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKStudentMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Reflection;
    using System.Text;
    using StudentLib.Services;
    using System.Linq;
    using System.Diagnostics;

    public partial class RuleModel
    {
        public RuleModel() { }
        public RuleModel(IValidationRule rule)
        {
            FullName = rule.GetType().FullName;
            Description = rule.Description;
            Active = true;
        }
        public string FullName { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }

        public override string ToString()
        {
            Type objType = this.GetType();
            PropertyInfo[] propertyInfoList = objType.GetProperties();
            StringBuilder result = new StringBuilder();
            foreach (var propertyInfo in propertyInfoList)
            {
                result.Append($"{propertyInfo.Name}={propertyInfo.GetValue(this)}, ");
            }
            return result.ToString();
        }

        public virtual bool InEffect()
        {
            try
            {
                var ruleType = Type.GetType(FullName);
                if (StartDate == null && EndDate == null && Active)
                {
                    return true;
                }
                if (StartDate != null)
                {
                    if (StartDate > DateTime.Now)
                    {
                        return false;
                    }

                    if (StartDate <= DateTime.Now && Active)
                    {
                        if (EndDate == null)
                        {
                            return true;
                        }
                        if (EndDate > DateTime.Now)
                        {
                            return true;
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex.StackTrace);
            }
            return false;
        }
    }

}
