// <auto-generated />
namespace BKStudentMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class ProvinceAndBalance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProvinceAndBalance));
        
        string IMigrationMetadata.Id
        {
            get { return "201910080902403_ProvinceAndBalance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
